version: '3.6'
services:
  influxdb:
    image: influxdb:1.8
    env_file: configuration.env
    ports:
      - '8086:8086'
    volumes:
      #- ./:/imports
      - influxdb-storage:/var/lib/influxdb

  chronograf:
    image: chronograf:latest
    env_file: configuration.env
    ports:
      - '8888:8888'
    volumes:
      - chronograf-storage:/var/lib/chronograf
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana:latest
    env_file: configuration.env
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
    depends_on:
      - influxdb
  
  viessmannapi:
    build:
      context: externals/docker/container/docker_corn_python
      dockerfile: Dockerfile
    image: viessmannapiimage
    #volumes:
      #- ./externals/docker/container/docker_corn_python/etc/crontab:/etc/cron.d/jobs
      #- ./externals/python/Viessmann_API_InfluxDB_Logger:/home/python/viessmannAPI
    depends_on:
      - influxdb
    links:
      - influxdb

  telegraf:
    image: chronograf:1.8
    volumes:
      - ./telegraf/etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
      - '8125:8125/udp'
      
  #telegraf:
  #  image: telegraf:1.18
  #  volumes:
  #  - ./telegraf/etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
  #  depends_on:
  #    - influxdb
  #  links:
  #    - influxdb
  #  ports:
  #  - '8125:8125/udp'

volumes:
  grafana-storage: {}
  influxdb-storage: {}
  chronograf-storage: {}
  viessmann-storage: {}