{
 "title": "ViessmanDashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "databaseVSM", "query": "influxdb" },
   { "name": "databaseOWM", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "name",
     "groupBy": [
      { "params": [ "tag_2" ], "type": "tag" }
     ],
     "measurement": "heating.circuits.1",
     "select": [
      [
       { "params": [ "name" ], "type": "field" },
       { "params": [ "value" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "mode_active",
     "groupBy": [
      { "params": [ "tag_2" ], "type": "tag" }
     ],
     "measurement": "heating.circuits.1.operating.modes.active",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "state_pump",
     "groupBy": [
      { "params": [ "tag_2" ], "type": "tag" }
     ],
     "measurement": "heating.circuits.1.circulation.pump",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       { "params": [ "value" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "name",
     "groupBy": [
      { "params": [ "tag2" ], "type": "tag" }
     ],
     "measurement": "heating.circuits.2",
     "select": [
      [
       { "params": [ "name" ], "type": "field" },
       { "params": [ "value" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "tag2" ], "type": "tag" }
     ],
     "measurement": "heating.circuits.2.circulation.pump",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       { "params": [ "value" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Circuit",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "heating.circuits.1",
     "select": [
      [
       { "params": [ "name" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Circuit",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "heating.circuits.2",
     "select": [
      [
       { "params": [ "name" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 10 },
   "targets": [
    {
     "alias": "pump",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "heating.circuits.1.circulation.pump",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "heating.circuits.1.frostprotection",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "heating.circuits.1.operating.modes.active",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {}
   ]
  },
  {
   "title": "Panel Title",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 10 },
   "targets": [
    {
     "alias": "pump",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "heating.circuits.1.circulation.pump",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Curcuits", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  { "title": "Global Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "States",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "alias": "Burner",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "heating.burners.0",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Circuit_1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "heating.circuits.1",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Pump_1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "heating.circuits.1.circulation.pump",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Circuit_2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "heating.circuits.2",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Pump_2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "heating.circuits.2.circulation.pump",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Status Burner",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "heating.burners.0",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Status Heating_1",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "heating.circuits.1",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Status Heating_2",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "heating.circuits.2",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  { "title": "IDs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Device Serial",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "device.serial",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Boilder Serial",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "heating.boiler.serial",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "alias": "Boiler",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "heating.boiler.temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Outside",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "heating.sensors.temperature.outside",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Collector",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "heating.solar.sensors.temperature.collector",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "DHW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "heating.solar.sensors.temperature.dhw",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Storage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "heating.dhw.sensors.temperature.hotWaterStorage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "CommonSupply",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "heating.boiler.sensors.temperature.commonSupply",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "C1_Supply",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "heating.circuits.1.sensors.temperature.supply",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "C2_Supply",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "heating.circuits.2.sensors.temperature.supply",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "owmTemperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}